# 노드 이미지를 최신 버전으로 가져옴
FROM node:20.10.0 as build

## npm install & build
WORKDIR /app
COPY . .

# Set npm cache location to avoid ENOSPC errors
RUN npm config set cache /tmp/npm-cache --global

# Clean npm cache to avoid potential issues
RUN npm cache clean --force

RUN npm install
RUN npm run build:prod --verbose

# nginx 설치
FROM nginx:stable-alpine

# 빌드한 폴더를 nginx의 html 으로 Copy
COPY --from=build /app/build /usr/share/nginx/html

# 충돌을 위한 기본 conf 파일 삭제
RUN rm /etc/nginx/conf.d/default.conf

# 커스텀으로 작성한 nginx 설정파일 Copy
COPY nginx/nginx.conf /etc/nginx/conf.d

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]